[
    {
        "api": "__exception__",
        "arguments": {
            "stacktrace": "481+0x402df @ 0x4402df\nBaseThreadInitThunk+0x19 FindResourceExW-0x197 kernel32+0x1fa29 @ 0x75f9fa29\nRtlGetAppContainerNamedObjectPath+0x11e RtlInitializeExceptionChain-0x12 ntdll+0x67a4e @ 0x77467a4e\nRtlGetAppContainerNamedObjectPath+0xee RtlInitializeExceptionChain-0x42 ntdll+0x67a1e @ 0x77467a1e",
            "registers": {
                "esp": 1702792,
                "edi": 6381752,
                "eax": 0,
                "ebp": 1703592,
                "edx": 2568192,
                "ebx": 260,
                "esi": 4568480,
                "ecx": 25
            },
            "exception": {
                "instruction_r": "80 20 00 59 59 89 45 fc 8d 85 f8 fe ff ff 53 50",
                "symbol": "481+0x4033b",
                "instruction": "and byte ptr [eax], 0",
                "module": "481.exe",
                "exception_code": "0xc0000005",
                "offset": 262971,
                "address": "0x44033b"
            }
        }
    }
]